package models;

public enum ValidationState
{
	VALID,
	NOT_VALID_NO_INPUT_FOUND,
	NOT_VALID_START_IS_AFTER_END,
	NOT_VALID_WORKSEGMENTS_MUST_BE_IN_CHRONICAL_ORDER,
	NOT_VALID_BREAK_IS_NOT_IN_WORKTIME,
	NOT_VALID_SELECTED_DAY_IS_IN_THE_FUTURE,
	NOT_VALID_SELECTED_DAY_IS_TO_FAR_IN_THE_PAST
}